backend:
  name: git-gateway
  branch: main

media_folder: images

collections:
  - name: resources
    label: Resources
    folder: data/contacts
    create: true
    fields:
      - label: Organization Name
        name: title
        widget: string
      - label: Phone Number
        name: phone
        widget: string
      - label: Address
        name: address
        widget: string
      - label: Hours
        name: hours
        widget: string
      - label: Notes
        name: notes
        widget: text
        required: false
